project:
  type: book

book:
  title: "Econometrics with the Tidyverse"
  subtitle: "A Flipped Classroom Experience"
  author: "Colleen O'Briant"
  date: "8/14/2022"
  chapters:
    - part: index.qmd
      chapters:
        - materials.qmd
        - schedule.qmd
        - programming_philosophy.qmd
        - workspace_setup.qmd
    - part: OLS Basics
      chapters:
        - least_squares.qmd
        - exogeneity.qmd
        - causal_inference.qmd
        - consistency.qmd
        - specification.qmd
        - heteroskedasticity.qmd
    - part: Topics in Time Series
      chapters:
        - time_series.qmd
        - stationarity.qmd
    - part: Extensions
      chapters:
        - instrumental_vars.qmd
        - IV_2.qmd
        - diff_in_diff.qmd
    - part: summary.qmd
      chapters:
        - classwork.qmd
        - koans.qmd
        - math.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    codecopy: true
  pdf:
    documentclass: scrreprt



