# Programming Philosophy  {.unnumbered}

We learn to program (same as we learn anything) by forming a mental model of how the framework works, and then trying to use the framework to solve our own problems (practicing syntax). Sadly, there are lots of ways you can go wrong here: wrong syntax is pretty obvious because you'll get errors, but wrong mental models can stick around for a lifetime and they make programming a real uphill battle.

I've spent a lot of time over the past 3 years (and I've taken a lot of time from the smartest programmers and R people I know) to get this part of the course right. Hopefully you'll find that solving problems using the tidyverse is simple, easy, and natural. But if you skim through the koans and do them as fast as possible, things will not work out! Remember, the koans aren't busywork to be done for speed. They will help you build your mental model and learn the syntax, but only if you take your time, read them carefully, and reflect. 

## Declarative vs Imperative Programming

One wrong way of programming in the tidyverse is to mix paradigms (declarative and imperative). The tidyverse is declarative. But you'll see a lot of R code online that's imperative, which is written in base R. Mixing the two paradigms makes for confusing, complicated code.

Declarative vs imperative: what's the difference? Imperative programming is relatively low-level: you think in terms of manipulating values using for loops and if statements. Declarative programming is programming at a higher abstraction level: you make use of handy functions (AKA abstractions) to manipulate large swaths of data at one time instead of going value-by-value.

A good metaphor for the difference between imperative and declarative programming is this: suppose I'm trying to help you drive from your house to school. Imperative programming is when I send you turn-by-turn directions, and declarative programming is when I tell you to just put "University of Oregon" into your GPS. With declarative programming, I can declare *what I want you to do* without telling you exactly *how I want you to do it* like with imperative programming. Telling you to put "University of Oregon" into your GPS has advantages over giving you turn-by-turn directions: the GPS may have information about traffic and road closures that I'm not aware of. And the declarative approach is much easier for me: I could help the whole class get from their houses to the university by telling everyone to put "University of Oregon" into their GPS's, while sending each person their own set of turn-by-turn instructions would be a lot more work. 

Likewise, when you use the tidyverse's abstractions like `filter()`, `mutate()`, `map()`, `reduce()`, and all of ggplot2's great plotting functions, you're taking advantage of the fact that the engineers who built those functions know tricks in R that you may not be aware of to make things run smoothly. And when you're programming declaratively, you can continue thinking about your problem at a high level instead of getting weighed down by nitty-gritty details. When it comes to data analysis, declarative programming has a lot of huge benefits.

But under the hood, all these great tidyverse functions are just a few for loops and if statements. Imperative programming certainly has its time and place, and that time and place is when your problems include implementing an *algorithm* by hand. If you're interested, I highly recommend [Project Euler](https://projecteuler.net/about) for teaching yourself imperative programming. But imperative programming is not something you'll need in this workbook. You may have mixed declarative with imperative programming in previous classes, but we'll stay strictly in the declarative territory in this class.

## Things to Avoid when Programming Declaratively in the Tidyverse

Use these only when you're programming imperatively in base R:

- for loops (we'll use `map()` instead)
- if statements (we'll use the vectorized function from dplyr `if_else()`)
- `matrix()` (our 2d data structure of choice is the `tibble()`)
- `$` syntax for extracting a column vector from a tibble. We avoid this because our workflow goes like this: vectors go into tibbles and we do data analysis on *tibbles*. Going from tibbles to vectors (what `$` lets you do) is the reverse of what we need, so we avoid it in this class. It just causes unnecessary headaches!

One more thing: I often see students using assignment `<-` wayyyy too much. If you're creating a variable for something, and you only use that thing one other time, and naming that thing doesn't help the readability of your code, why are you creating that variable? If you let your default be "no assignment" instead of "always assignment", then your code will be much prettier and your global environment will stay clean, which prevents lots of confusion.

## Your Approach

 When you're stuck on a hard problem, here are the steps I recommend:

 1. Get crystal clear about the problem you're trying to solve. Write out what you *have* versus what you *want*.

 2. Break the problem into small steps and make a plan about how you're going to do each step.

 3. Not sure about how to do a certain step? *Don't* just guess wildly and stop googling every problem you're stuck on. And **get the hell off of stack overflow!** The solutions on that site are usually written imperatively in base R, they sometimes pre-date the tidyverse, and even if they work, they won't help your understanding. Instead, get in the habit of reading the help docs for functions. I've created a package called `qelp` (quick help) which is just beginner friendly help docs for almost all the functions you'll need in this class.

## What is "Good Code"?

 What are we trying to do here?

 First, come to terms with the fact that there's no such thing as good code. All code is bad code, and it's OK! You can't be a perfectionist with this stuff.

 But *really bad* code is code that is unnecessarily complicated. If you want examples, just check out stackoverflow! We should always be striving to write simple, elegant solutions because those are easy for others to read and understand, easy for *ourselves* to read and understand, they're easy for a data engineer at your future company to optimize, and when something is broken, it's easy to debug.

 Let's not get ahead of ourselves though! Good code, first and foremost, solves the problem at hand! If your solution works, you can always just leave it there. That is sometimes the best thing you can do for your sanity.

 + Good code...
   + Solves the problem.
   + Solves the problem in the simplest way.
   + Solves the problem in the simplest way, that's also clear and readable for others.
   + Solves the problem in the simplest way, that's also clear and readable for others, with comments that tell readers why you're doing what you're doing.
